# -*- coding: utf-8 -*-
"""WC_NNLCI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kofFmuvoAtalRMSVPgo_k11XFKpbW5m
"""

# install python of Design Of Experiment
#!pip install --upgrade pyDOE

import torch
import torch.autograd as autograd
from torch import Tensor
import torch.nn as nn
import torch.optim as optim
from collections import OrderedDict

import numpy as np
import matplotlib.pyplot as plt
import scipy.io
from scipy.interpolate import griddata
# from pyDOE import lhs
# from plotting import newfig, savefig
from mpl_toolkits.mplot3d import Axes3D
import time
import matplotlib.gridspec as gridspec
from mpl_toolkits.axes_grid1 import make_axes_locatable

np.random.seed(1234)

# Torch random number
torch.manual_seed(1234)

# Set the default dtype as float32
torch.set_default_dtype(torch.float)

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)

if device == 'CUDA':
  print(torch.cuda.get_device_name())

torch.cuda.get_device_name(0)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
!ls "/content/drive/My Drive"
root_dir = "/content/drive/My Drive/"

train_100 = np.load(root_dir+'WC_NNLCI/training_dataset_100.npy')
train_200 = np.load(root_dir+'WC_NNLCI/training_dataset_200.npy')
train_1600 = np.load(root_dir+'WC_NNLCI/training_dataset_hf.npy')
train_1600 = train_1600.reshape((401,1600,3))

test_100 = np.load(root_dir+'WC_NNLCI/testing_dataset_100.npy')
test_200 = np.load(root_dir+'WC_NNLCI/testing_dataset_200.npy')
test_1600 = np.load(root_dir+'WC_NNLCI/testing_dataset_hf.npy')
test_1600 = test_1600.reshape((100,1600,3))

train_100_new = []; train_200_new = []; train_1600_new = []
for i in range(40):
    train_100_new.append(train_100[10*i,:,:])
    train_200_new.append(train_200[10*i,:,:])
    train_1600_new.append(train_1600[10*i,:,:])
train_100 = np.array(train_100_new); train_200 = np.array(train_200_new); train_1600 = np.array(train_1600_new);

train_coarse = train_100; train_finer = np.copy(train_100); train_hf = np.copy(train_100);
test_coarse = test_100; test_finer = np.copy(test_100); test_hf = np.copy(test_100);

for i in range(100):
    train_finer[:,i,:] = train_200[:,int(2*i),:]
    train_hf[:,i,:] = train_1600[:,int(16*i),:]

    test_finer[:,i,:] = test_200[:,int(2*i),:]
    test_hf[:,i,:] = test_1600[:,int(16*i),:]

train_coarse = np.log10(train_coarse+2)
train_finer  = np.log10(train_finer+2)
train_hf  = np.log10(train_hf+2)

test_coarse  = np.log10(test_coarse+2)
test_finer = np.log10(test_finer+2)
test_hf  = np.log10(test_hf+2)

ub = np.max(np.max(train_coarse,axis=0),axis=0)
lb = np.min(np.min(train_coarse,axis=0),axis=0)

train_coarse = 2*(train_coarse-lb)/(ub-lb)-1; test_coarse = 2*(test_coarse-lb)/(ub-lb)-1;
train_finer = 2*(train_finer-lb)/(ub-lb)-1; test_finer = 2*(test_finer-lb)/(ub-lb)-1;
train_hf = 2*(train_hf-lb)/(ub-lb)-1; test_hf = 2*(test_hf-lb)/(ub-lb)-1;

var = 'all'
train_input = []; train_output = []
test_input = []; test_output = []
for i in range(98):
    train1 = train_coarse[:,i:i+3,:]; train2 = train_finer[:,i:i+3,:]; train3 = train_hf[:,i+1,:];
    train4 = np.concatenate((train1,train2),axis=1); train4 = train4.reshape((40,-1))
    train_input.append(train4); train_output.append(train3)

    test1 = test_coarse[:,i:i+3,:]; test2 = test_finer[:,i:i+3,:]; test3 = test_hf[:,i+1,:];
    test4 = np.concatenate((test1,test2),axis=1); test4 = test4.reshape((100,-1))
    test_input.append(test4); test_output.append(test3)

train_input = np.array(train_input); train_input = train_input.reshape((-1,18));
train_output = np.array(train_output); train_output = train_output.reshape((-1,3))
test_input = np.array(test_input); test_input = test_input.reshape((-1,18));
test_output = np.array(test_output); test_output = test_output.reshape((-1,3))

# Set up Deep Neural Network
class neural_net(nn.Module):
    def __init__(self, layers):
        super(neural_net, self).__init__()

        # Parameters
        # i). Num. of hidden layers
        self.depth = len(layers) - 1

        # ii). activation function
        self.actfunc = nn.Tanh()

        # iii). Initialize the neural network as a list using nn.Modulelist
        self.linears = nn.ModuleList([nn.Linear(layers[i], layers[i+1]) for i in range(self.depth)])

        # iv). initialize the parameters
        for i in range(self.depth):

            # 1. Xavier normalization
            nn.init.xavier_normal_(self.linears[i].weight.data, gain = 5.0/3.0)

            # 2. set biases as zeros
            nn.init.zeros_(self.linears[i].bias.data)

    "foward pass"
    def forward(self, x):

        if torch.is_tensor(x) != True:
            x = torch.from_numpy(x)

        # u_b = torch.from_numpy(ub).float().to(device)
        # l_b = torch.from_numpy(lb).float().to(device)

        #preprocessing input
        # x = (x - l_b)/(u_b - l_b) #feature scaling

        #convert to float
        a = x.float()

        for i in range(self.depth - 1):
            z = self.linears[i](a)
            a = self.actfunc(z)

        a = self.linears[-1](a)

        return a

if var == 0:
    model_name = 'WC_NNLCI/WC_NNLCI_density_40cases'
if var == 1:
    model_name = 'WC_NNLCI/WC_NNLCI_velocity_40cases'
if var == 2:
    model_name = 'WC_NNLCI/WC_NNLCI_pressure_40cases'
else:
    model_name = 'WC_NNLCI/WC_NNLCI_all_40cases'

class MFNN_2D_Riemann():
    def __init__(self, train_input, train_output, layers, lrate, reg):

        #########################################################
        ######### Convert all numpy data to torch tensor ########
        #########################################################

        # ii. input data and training data
        # 1. Input Data
        self.Train_input = torch.tensor(train_input).float().to(device)

        # 2. Training hf Data
        self.Train_hf = torch.tensor(train_output).float().to(device)
        self.layers = layers

        # Call deep neural networks
        self.net_u = neural_net(self.layers).to(device)

        # optimizers Adams
        # 1. Adam optimizer
        self.optimizer_Adam = torch.optim.Adam(self.net_u.parameters(), lr = lrate, weight_decay = reg)

        # 2. start with number of iterations as zero
        self.iter = 0


    def train(self, nIter):
        # Adam Optimizer
        self.net_u.train()
        state_dict = torch.load(root_dir+model_name)
        self.net_u.load_state_dict(state_dict)

        start_time = time.time()
        # I. Adam Optimizer
        for epoch in range(nIter):

           # i). Prediction from neural network
           self.dat_pred = self.net_u(self.Train_input)

           # ii). define loss function
           loss_fcn = torch.nn.MSELoss()
           target = torch.zeros((self.Train_hf.size(0),self.Train_hf.size(1))).to(device)
           #loss = loss_fcn(self.Train_hf,self.dat_pred)
           loss = loss_fcn(self.Train_hf,self.dat_pred)/loss_fcn(self.Train_hf,target)



           # v). backward and optimize
           self.optimizer_Adam.zero_grad()
           loss.backward()
           self.optimizer_Adam.step()

           # start_time = time.time()

           if epoch % 100 == 0:
              elapsed = time.time() - start_time
              print('Number of Iterations: %d, Loss: %.3e, Time Elapsed: %.5f' %
                      (epoch, loss.item(), elapsed))

              start_time = time.time()
              torch.save(self.net_u.state_dict(), root_dir+model_name)


    def predict(self, input_dat_star):

        # 1. Predictive
        self.input_dat_star_o = torch.tensor(input_dat_star).float().to(device)

        # Prediction
        dat_hf_star = self.net_u(self.input_dat_star_o)

        return dat_hf_star

nIter = 10000
layers = [18] + 10*[300] + [3]
lr = 1e-6
reg = 1e-8

model = MFNN_2D_Riemann(train_input, train_output, layers, lr, reg)

# Initialize the training process
start_time = time.time()

model.train(nIter)
elapsed = time.time() - start_time
torch.cuda.get_device_name(0)
print('Training time: %.4f' % (elapsed))

print(ub)

output = model.predict(test_input)
output = output.detach().cpu().numpy()

# test_prime = (test_output+1)*(ub-lb)/2+lb
# output = (output+1)*(ub-lb)/2+lb

test_prime = test_output

if var == 0:
    ub_var = ub[0]
    lb_var = lb[0]
    output = (output+1)*(ub_var-lb_var)/2+lb_var
    output = 10**(output)-2
    test_prime = (test_prime+1)*(ub_var-lb_var)/2+lb_var
    test_prime = 10**(test_prime)-2
if var == 1:
    output = 10**(output)-1e-1
    test_prime = 10**(test_output)-1e-1;
if var == 2:
    output = 10**(output)-1e-1
    test_prime = 10**(test_output)-1e-1;
if var == 'all':
    output = (output+1)*(ub-lb)/2+lb
    output = 10**(output)-2
    test_prime = (test_prime+1)*(ub-lb)/2+lb
    test_prime = 10**(test_prime)-2

print(np.shape(output),np.shape(test_output))

mse_loss = np.sqrt(np.sum((test_prime - output)**2,axis=0))/np.sqrt(np.sum(test_prime**2,axis=0))

L1_loss = np.linalg.norm(test_prime - output, ord=1 ,axis = 0)/np.linalg.norm(test_prime, ord=1, axis=0)

print(L1_loss)
print(mse_loss)


# np.save(root_dir+'WC_NNLCI/testingprime_dataset_50.npy',test_prime)
# np.save(root_dir+'WC_NNLCI/output_dataset_50.npy',output)

print(np.shape(output))

if var == 0:
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_density.npy',output)
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_density.npy',test_prime)
if var == 1:
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_velocity.npy',output)
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_velocity.npy',test_prime)
if var == 2:
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_pressure.npy',output)
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_pressure.npy',test_prime)
if var == 'all':
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_density.npy',output[:,0])
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_density.npy',test_prime[:,0])

    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_velocity.npy',output[:,1])
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_velocity.npy',test_prime[:,1])

    np.save(root_dir+'WC_NNLCI/WC_NNLCI_pred_pressure.npy',output[:,2])
    np.save(root_dir+'WC_NNLCI/WC_NNLCI_test_pressure.npy',test_prime[:,2])